#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF202971DA4A79E2C (bremner@unb.ca)
#
Name     : notmuch
Version  : 0.29.1
Release  : 23
URL      : https://notmuchmail.org/releases/notmuch-0.29.1.tar.xz
Source0  : https://notmuchmail.org/releases/notmuch-0.29.1.tar.xz
Source99 : https://notmuchmail.org/releases/notmuch-0.29.1.tar.xz.asc
Summary  : Notmuch is not much of an email program
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+ LGPL-2.1
Requires: notmuch-bin = %{version}-%{release}
Requires: notmuch-data = %{version}-%{release}
Requires: notmuch-lib = %{version}-%{release}
Requires: notmuch-license = %{version}-%{release}
Requires: notmuch-man = %{version}-%{release}
Requires: talloc-lib
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : gmime
BuildRequires : gmime-dev
BuildRequires : gnupg
BuildRequires : ruby
BuildRequires : talloc
BuildRequires : talloc-dev
BuildRequires : valgrind
BuildRequires : xapian-core-dev
BuildRequires : zlib
BuildRequires : zlib-dev
Patch1: dont-fail-on-unrecognized-option.patch

%description
Fast system for indexing, searching, and tagging email.  Even if you
receive 12000 messages per month or have on the order of millions of
messages that you've been saving for decades, Notmuch will be able to
quickly search all of it.

Notmuch is not much of an email program. It doesn't receive messages
(no POP or IMAP support). It doesn't send messages (no mail composer,
no network code at all). And for what it does do (email search) that
work is provided by an external library, Xapian. So if Notmuch
provides no user interface and Xapian does all the heavy lifting, then
what's left here? Not much.

%package bin
Summary: bin components for the notmuch package.
Group: Binaries
Requires: notmuch-data = %{version}-%{release}
Requires: notmuch-license = %{version}-%{release}

%description bin
bin components for the notmuch package.


%package data
Summary: data components for the notmuch package.
Group: Data

%description data
data components for the notmuch package.


%package dev
Summary: dev components for the notmuch package.
Group: Development
Requires: notmuch-lib = %{version}-%{release}
Requires: notmuch-bin = %{version}-%{release}
Requires: notmuch-data = %{version}-%{release}
Provides: notmuch-devel = %{version}-%{release}
Requires: notmuch = %{version}-%{release}
Requires: notmuch = %{version}-%{release}

%description dev
dev components for the notmuch package.


%package lib
Summary: lib components for the notmuch package.
Group: Libraries
Requires: notmuch-data = %{version}-%{release}
Requires: notmuch-license = %{version}-%{release}

%description lib
lib components for the notmuch package.


%package license
Summary: license components for the notmuch package.
Group: Default

%description license
license components for the notmuch package.


%package man
Summary: man components for the notmuch package.
Group: Default

%description man
man components for the notmuch package.


%prep
%setup -q -n notmuch-0.29.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560308439
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1560308439
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/notmuch
cp COPYING %{buildroot}/usr/share/package-licenses/notmuch/COPYING
cp COPYING-GPL-3 %{buildroot}/usr/share/package-licenses/notmuch/COPYING-GPL-3
cp bindings/python/docs/COPYING %{buildroot}/usr/share/package-licenses/notmuch/bindings_python_docs_COPYING
cp contrib/go/LICENSE %{buildroot}/usr/share/package-licenses/notmuch/contrib_go_LICENSE
cp debian/copyright %{buildroot}/usr/share/package-licenses/notmuch/debian_copyright
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/notmuch
/usr/bin/notmuch-emacs-mua

%files data
%defattr(-,root,root,-)
/usr/share/emacs/site-lisp/coolj.el
/usr/share/emacs/site-lisp/notmuch-address.el
/usr/share/emacs/site-lisp/notmuch-company.el
/usr/share/emacs/site-lisp/notmuch-compat.el
/usr/share/emacs/site-lisp/notmuch-crypto.el
/usr/share/emacs/site-lisp/notmuch-draft.el
/usr/share/emacs/site-lisp/notmuch-hello.el
/usr/share/emacs/site-lisp/notmuch-jump.el
/usr/share/emacs/site-lisp/notmuch-lib.el
/usr/share/emacs/site-lisp/notmuch-logo.png
/usr/share/emacs/site-lisp/notmuch-maildir-fcc.el
/usr/share/emacs/site-lisp/notmuch-message.el
/usr/share/emacs/site-lisp/notmuch-mua.el
/usr/share/emacs/site-lisp/notmuch-parser.el
/usr/share/emacs/site-lisp/notmuch-print.el
/usr/share/emacs/site-lisp/notmuch-query.el
/usr/share/emacs/site-lisp/notmuch-show.el
/usr/share/emacs/site-lisp/notmuch-tag.el
/usr/share/emacs/site-lisp/notmuch-tree.el
/usr/share/emacs/site-lisp/notmuch-version.el
/usr/share/emacs/site-lisp/notmuch-wash.el
/usr/share/emacs/site-lisp/notmuch.el
/usr/share/zsh/functions/Completion/Unix/_email-notmuch
/usr/share/zsh/functions/Completion/Unix/_notmuch

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libnotmuch.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnotmuch.so.5
/usr/lib64/libnotmuch.so.5.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/notmuch/COPYING
/usr/share/package-licenses/notmuch/COPYING-GPL-3
/usr/share/package-licenses/notmuch/bindings_python_docs_COPYING
/usr/share/package-licenses/notmuch/contrib_go_LICENSE
/usr/share/package-licenses/notmuch/debian_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/notmuch-address.1.gz
/usr/share/man/man1/notmuch-compact.1.gz
/usr/share/man/man1/notmuch-config.1.gz
/usr/share/man/man1/notmuch-count.1.gz
/usr/share/man/man1/notmuch-dump.1.gz
/usr/share/man/man1/notmuch-emacs-mua.1.gz
/usr/share/man/man1/notmuch-insert.1.gz
/usr/share/man/man1/notmuch-new.1.gz
/usr/share/man/man1/notmuch-reindex.1.gz
/usr/share/man/man1/notmuch-reply.1.gz
/usr/share/man/man1/notmuch-restore.1.gz
/usr/share/man/man1/notmuch-search.1.gz
/usr/share/man/man1/notmuch-setup.1.gz
/usr/share/man/man1/notmuch-show.1.gz
/usr/share/man/man1/notmuch-tag.1.gz
/usr/share/man/man1/notmuch.1.gz
/usr/share/man/man5/notmuch-hooks.5.gz
/usr/share/man/man7/notmuch-properties.7.gz
/usr/share/man/man7/notmuch-search-terms.7.gz
